name: run_tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - smoke_UI
          - regression_UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: maven

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: smoke_UI
        if: "github.event.inputs.deployment_target == 'smoke_UI'"
        run: mvn clean -Dtest=CourierCreateTest.java test

      - name: regression_UI
        if: "github.event.inputs.deployment_target == 'regression_UI'"
        run: mvn clean -Dtest=CourierLoginTest.java test

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          if-no-files-found: error
          retention-days: 1

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure

      - name: Download all workflow tun artifacts
        uses: actions/download-artifact@v4
      - run: mvn allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1


  publish-report:
      runs-on: ubuntu-latest
      needs: generate-report
      name: Report publication
      steps:
        - name: Download all workflow run artifacts
          uses: actions/download-artifact@v4
        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4



