name: run_tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - smoke_UI
          - regression_UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 22
          cache: maven

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: smoke_UI
        if: "github.event.inputs.deployment_target == 'smoke_UI'"
        run: mvn clean -Dtest=CourierCreateTest.java test

      - name: regression_UI
        if: "github.event.inputs.deployment_target == 'regression_UI'"
        run: mvn clean -Dtest=CourierLoginTest.java test

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path:
            allure-results
          retention-days: 1

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: develop
          path: develop

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: develop
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: develop
          publish_dir: allure-history


